version: '3.4'

services:

  web:
    image: ajp3s/tonys-hardware
    build: .
    command: gunicorn --bind=0.0.0.0:8000 TonysHardware_v2.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /tmp/tonys_hardware/static:/app/static

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/tonys_hardware/static:/home/app/web/staticfiles/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web