# Generated by Django 4.2.3 on 2023-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('cores_count', models.CharField(max_length=150)),
                ('base_clock', models.PositiveIntegerField()),
                ('boost_clock', models.PositiveIntegerField()),
                ('L1_cache', models.PositiveIntegerField()),
                ('L2_cache', models.PositiveIntegerField()),
                ('L3_cache', models.PositiveIntegerField()),
                ('tdp', models.PositiveIntegerField(verbose_name='Thermal Design Power(TDP)')),
                ('cpu_image', models.ImageField(upload_to='cpu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='NvidiaGPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('graphics_processor', models.CharField(max_length=20)),
                ('architecture', models.CharField(max_length=20)),
                ('process_size', models.CharField(max_length=5)),
                ('transistors', models.CharField(max_length=30)),
                ('base_clock', models.PositiveIntegerField()),
                ('boost_clock', models.PositiveIntegerField()),
                ('memory_clock', models.PositiveIntegerField()),
                ('memory_bus_width', models.PositiveIntegerField()),
                ('bandwidth', models.PositiveIntegerField()),
                ('release_date', models.DateField(auto_now=True)),
                ('tdp', models.PositiveIntegerField(verbose_name='Thermal Design Power(TDP)')),
                ('suggested_psu', models.CharField(max_length=10)),
                ('graphics_api_support', models.CharField(max_length=60)),
                ('nvidia_gpu_image', models.ImageField(upload_to='nvidia_gpu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('ABS', 'ABS'), ('Antec', 'Antec'), ('AOpen', 'AOpen'), ('Apevia', 'Apevia'), ('AXLE', 'AXLE'), ('Be quiet!', 'Be quiet!'), ('Black Box', 'Black Box'), ('Cooler Master', 'Cooler Master'), ('Coolmax', 'Coolmax'), ('Corsair', 'Corsair'), ('Curtiss-Wright', 'Curtiss-Wright'), ('Deepcool', 'Deepcool'), ('Delta Electronics', 'Delta Electronics'), ('Dynapower USA', 'Dynapower USA'), ('Eaton', 'Eaton'), ('Emerson Network Power', 'Emerson Network Power'), ('EVGA', 'EVGA'), ('Foxconn', 'Foxconn'), ('G.SKILL', 'G.SKILL'), ('LIAN LI', 'LIANLI'), ('NZXT', 'NZXT'), ('Phanteks', 'Phanteks'), ('Qualstar', 'Qualstar'), ('RIOTORO', 'RIOTORO'), ('Rosewill', 'Rosewill'), ('Seasonic', 'Seasonic'), ('SIIG', 'SIIG'), ('Shuttle', 'Shuttle'), ('Supermicro', 'Supermicro'), ('TDK', 'TDK'), ('Thermaltake', 'Thermaltake'), ('UMEC', 'UMEC'), ('Vertiv', 'Vertiv'), ('XFX', 'XFX')], max_length=50, null=True)),
                ('max_dc_output', models.PositiveIntegerField()),
                ('modular', models.CharField(choices=[('Fully modular', 'Fully modular'), ('Semi-modular', 'Semi-modular'), ('Non-modular', 'Non-modular')], max_length=50, null=True)),
                ('connectors', models.TextField(max_length=200, null=True)),
                ('psu_image', models.ImageField(upload_to='psu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='RAMMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Micron', 'Micron'), ('Kingston', 'Kingston'), ('Smart Modular', 'Smart Modular'), ('Mushkin', 'Mushkin'), ('Qimonda', 'Qimonda'), ('GeIL', 'GeIL'), ('Patriot', 'Patriot'), ('PNY', 'PNY'), ('Hynix', 'Hynix'), ('Samsung', 'Samsung'), ('G.Skill', 'G.Skill'), ('Transcend', 'Transcend'), ('Apacer', 'Apacer'), ('Corsair', 'Corsair'), ('Crucial', 'Crucial'), ('ADATA', 'ADATA'), ('Team Group', 'Team Group')], max_length=50)),
                ('ram_type', models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10)),
                ('ram_frequency', models.CharField(max_length=100)),
                ('ram_image', models.ImageField(upload_to='ram_images/')),
            ],
        ),
        migrations.CreateModel(
            name='StorageDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('Adata', 'Adata'), ('Corsair', 'Corsair'), ('Crucial', 'Crucial'), ('Gigabyte Aorus', 'Gigabyte Aorus'), ('HP', 'HP'), ('Intel', 'Intel'), ('Kingston', 'Kingston'), ('Micron', 'Micron'), ('Pioneer', 'Pioneer'), ('PNY', 'PNY'), ('Samsung', 'Samsung'), ('SanDisk', 'SanDisk'), ('Seagate', 'Seagate'), ('Western Digital', 'Western Digital'), ('Axle', 'Axle'), ('BIOSTAR', 'BIOSTAR'), ('G.SKILL', 'G.SKILL'), ('Plextor', 'Plextor'), ('Verbatim', 'Verbatim'), ('Viking', 'Viking')], max_length=50)),
                ('type', models.CharField(choices=[('nvme m.2 SSD', 'nvme m.2 SSD'), ('HDD', 'HDD'), ('2.5 sata SSD', '2.5 sata SSD')], max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('drive_image', models.ImageField(upload_to='storage_drivers_images/')),
            ],
        ),
    ]
