# Generated by Django 4.2.3 on 2023-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_alter_rammemorymodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('Team Group', 'Team Group'), ('ADATA', 'ADATA'), ('Smart Modular', 'Smart Modular'), ('Micron', 'Micron'), ('Qimonda', 'Qimonda'), ('Transcend', 'Transcend'), ('PNY', 'PNY'), ('GeIL', 'GeIL'), ('G.Skill', 'G.Skill'), ('Crucial', 'Crucial'), ('Patriot', 'Patriot'), ('Kingston', 'Kingston'), ('Hynix', 'Hynix'), ('Apacer', 'Apacer'), ('Samsung', 'Samsung'), ('Mushkin', 'Mushkin'), ('Corsair', 'Corsair')], max_length=50),
        ),
    ]
