# Generated by Django 4.2.3 on 2023-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_remove_amdradeongpumodel_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('PNY', 'PNY'), ('Apacer', 'Apacer'), ('Mushkin', 'Mushkin'), ('Transcend', 'Transcend'), ('G.Skill', 'G.Skill'), ('Qimonda', 'Qimonda'), ('Crucial', 'Crucial'), ('Smart Modular', 'Smart Modular'), ('Team Group', 'Team Group'), ('GeIL', 'GeIL'), ('Patriot', 'Patriot'), ('Hynix', 'Hynix'), ('Corsair', 'Corsair'), ('Kingston', 'Kingston'), ('ADATA', 'ADATA'), ('Micron', 'Micron'), ('Samsung', 'Samsung')], max_length=50),
        ),
    ]
