# Generated by Django 4.2.3 on 2023-08-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_rammemorymodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('ADATA', 'ADATA'), ('Apacer', 'Apacer'), ('Corsair', 'Corsair'), ('Crucial', 'Crucial'), ('G.Skill', 'G.Skill'), ('GeIL', 'GeIL'), ('Hynix', 'Hynix'), ('Kingston', 'Kingston'), ('Micron', 'Micron'), ('Mushkin', 'Mushkin'), ('PNY', 'PNY'), ('Patriot', 'Patriot'), ('Qimonda', 'Qimonda'), ('Samsung', 'Samsung'), ('Smart Modular', 'Smart Modular'), ('Team Group', 'Team Group'), ('Transcend', 'Transcend')], max_length=50),
        ),
    ]
