# Generated by Django 4.2.3 on 2023-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_rammemorymodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('Micron', 'Micron'), ('Smart Modular', 'Smart Modular'), ('Transcend', 'Transcend'), ('Team Group', 'Team Group'), ('Samsung', 'Samsung'), ('Mushkin', 'Mushkin'), ('ADATA', 'ADATA'), ('Hynix', 'Hynix'), ('Apacer', 'Apacer'), ('Kingston', 'Kingston'), ('Corsair', 'Corsair'), ('Crucial', 'Crucial'), ('Qimonda', 'Qimonda'), ('PNY', 'PNY'), ('G.Skill', 'G.Skill'), ('Patriot', 'Patriot'), ('GeIL', 'GeIL')], max_length=50),
        ),
    ]
