# Generated by Django 4.2.3 on 2023-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_alter_rammemorymodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('GeIL', 'GeIL'), ('Crucial', 'Crucial'), ('Qimonda', 'Qimonda'), ('Transcend', 'Transcend'), ('Patriot', 'Patriot'), ('Corsair', 'Corsair'), ('Samsung', 'Samsung'), ('PNY', 'PNY'), ('G.Skill', 'G.Skill'), ('ADATA', 'ADATA'), ('Mushkin', 'Mushkin'), ('Kingston', 'Kingston'), ('Hynix', 'Hynix'), ('Smart Modular', 'Smart Modular'), ('Team Group', 'Team Group'), ('Apacer', 'Apacer'), ('Micron', 'Micron')], max_length=50),
        ),
    ]
