# Generated by Django 4.2.3 on 2023-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_motherboard_alter_rammemory_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IntelGPUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NvmeSSDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SataSSDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='MotherBoard',
            new_name='MotherBoardModel',
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='brand',
            field=models.CharField(choices=[('Crucial', 'Crucial'), ('Corsair', 'Corsair'), ('Kingston', 'Kingston'), ('Samsung', 'Samsung'), ('Micron', 'Micron'), ('G.Skill', 'G.Skill'), ('Smart Modular', 'Smart Modular'), ('Team Group', 'Team Group'), ('Apacer', 'Apacer'), ('ADATA', 'ADATA'), ('PNY', 'PNY'), ('Patriot', 'Patriot'), ('GeIL', 'GeIL'), ('Hynix', 'Hynix'), ('Qimonda', 'Qimonda'), ('Transcend', 'Transcend'), ('Mushkin', 'Mushkin')], max_length=50),
        ),
    ]
