# Generated by Django 4.2.3 on 2023-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_motherboard_alter_rammemory_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotherBoard',
            new_name='MotherBoardModel',
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='brand',
            field=models.CharField(choices=[('Mushkin', 'Mushkin'), ('Apacer', 'Apacer'), ('Hynix', 'Hynix'), ('G.Skill', 'G.Skill'), ('Smart Modular', 'Smart Modular'), ('GeIL', 'GeIL'), ('Corsair', 'Corsair'), ('Micron', 'Micron'), ('Team Group', 'Team Group'), ('Transcend', 'Transcend'), ('PNY', 'PNY'), ('Kingston', 'Kingston'), ('ADATA', 'ADATA'), ('Samsung', 'Samsung'), ('Qimonda', 'Qimonda'), ('Crucial', 'Crucial'), ('Patriot', 'Patriot')], max_length=50),
        ),
    ]
