# Generated by Django 4.2.3 on 2023-08-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_rename_motherboard_motherboardmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psu',
            name='efficiency_standard',
            field=models.CharField(choices=[('80 Plus', '80 Plus'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Titanium', 'Titanium')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rammemory',
            name='capacity',
            field=models.PositiveIntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='brand',
            field=models.CharField(choices=[('ADATA', 'ADATA'), ('Hynix', 'Hynix'), ('Smart Modular', 'Smart Modular'), ('Patriot', 'Patriot'), ('Micron', 'Micron'), ('Apacer', 'Apacer'), ('G.Skill', 'G.Skill'), ('GeIL', 'GeIL'), ('Kingston', 'Kingston'), ('Crucial', 'Crucial'), ('Mushkin', 'Mushkin'), ('Corsair', 'Corsair'), ('PNY', 'PNY'), ('Transcend', 'Transcend'), ('Team Group', 'Team Group'), ('Qimonda', 'Qimonda'), ('Samsung', 'Samsung')], max_length=50),
        ),
    ]
