# Generated by Django 4.2.3 on 2023-08-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_alter_rammemorymodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amdradeongpumodel',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='amdradeongpumodel',
            name='series',
        ),
        migrations.AddField(
            model_name='amdradeongpumodel',
            name='ram_size',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('ADATA', 'ADATA'), ('Corsair', 'Corsair'), ('Transcend', 'Transcend'), ('G.Skill', 'G.Skill'), ('Apacer', 'Apacer'), ('Smart Modular', 'Smart Modular'), ('Team Group', 'Team Group'), ('Mushkin', 'Mushkin'), ('Kingston', 'Kingston'), ('Samsung', 'Samsung'), ('Patriot', 'Patriot'), ('PNY', 'PNY'), ('Micron', 'Micron'), ('Crucial', 'Crucial'), ('GeIL', 'GeIL'), ('Qimonda', 'Qimonda'), ('Hynix', 'Hynix')], max_length=50),
        ),
    ]
