# Generated by Django 4.2.3 on 2023-08-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_remove_amdradeongpumodel_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nvidiagpumodel',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='nvidiagpumodel',
            name='memory_bandwidth',
        ),
        migrations.RemoveField(
            model_name='nvidiagpumodel',
            name='memory_clock',
        ),
        migrations.RemoveField(
            model_name='nvidiagpumodel',
            name='series',
        ),
        migrations.AddField(
            model_name='nvidiagpumodel',
            name='ram_size',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nvidiagpumodel',
            name='release_price',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nvidiagpumodel',
            name='graphics_api_support',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='nvidiagpumodel',
            name='maximum_gpu_temperature',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='nvidiagpumodel',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nvidiagpumodel',
            name='suggested_psu',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('Hynix', 'Hynix'), ('Crucial', 'Crucial'), ('Samsung', 'Samsung'), ('ADATA', 'ADATA'), ('G.Skill', 'G.Skill'), ('Micron', 'Micron'), ('Patriot', 'Patriot'), ('Team Group', 'Team Group'), ('Qimonda', 'Qimonda'), ('Apacer', 'Apacer'), ('GeIL', 'GeIL'), ('PNY', 'PNY'), ('Transcend', 'Transcend'), ('Smart Modular', 'Smart Modular'), ('Mushkin', 'Mushkin'), ('Kingston', 'Kingston'), ('Corsair', 'Corsair')], max_length=50),
        ),
    ]
