# Generated by Django 4.2.3 on 2023-08-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_rename_amd_radeon_gpu_image_amdradeongpu_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='release_price',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='psu',
            name='release_price',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='rammemory',
            name='release_price',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='storagedrive',
            name='release_price',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='psu',
            name='connectors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='brand',
            field=models.CharField(choices=[('Corsair', 'Corsair'), ('Apacer', 'Apacer'), ('Qimonda', 'Qimonda'), ('G.Skill', 'G.Skill'), ('Transcend', 'Transcend'), ('Hynix', 'Hynix'), ('PNY', 'PNY'), ('Micron', 'Micron'), ('GeIL', 'GeIL'), ('Mushkin', 'Mushkin'), ('Patriot', 'Patriot'), ('Smart Modular', 'Smart Modular'), ('Samsung', 'Samsung'), ('Kingston', 'Kingston'), ('Team Group', 'Team Group'), ('ADATA', 'ADATA'), ('Crucial', 'Crucial')], max_length=50),
        ),
    ]
