# Generated by Django 4.2.3 on 2023-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_remove_nvidiagpumodel_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboardmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='motherboard_images'),
        ),
        migrations.AlterField(
            model_name='amdradeongpumodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nvidia_gpu_images/'),
        ),
        migrations.AlterField(
            model_name='cpumodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cpu_images/'),
        ),
        migrations.AlterField(
            model_name='nvidiagpumodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nvidia_gpu_images/'),
        ),
        migrations.AlterField(
            model_name='psumodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='psu_images/'),
        ),
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('G.Skill', 'G.Skill'), ('ADATA', 'ADATA'), ('Hynix', 'Hynix'), ('Samsung', 'Samsung'), ('Apacer', 'Apacer'), ('Smart Modular', 'Smart Modular'), ('PNY', 'PNY'), ('Corsair', 'Corsair'), ('Crucial', 'Crucial'), ('Mushkin', 'Mushkin'), ('Transcend', 'Transcend'), ('Kingston', 'Kingston'), ('GeIL', 'GeIL'), ('Patriot', 'Patriot'), ('Micron', 'Micron'), ('Team Group', 'Team Group'), ('Qimonda', 'Qimonda')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rammemorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ram_images/'),
        ),
        migrations.AlterField(
            model_name='storagedrivemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage_drives_images/'),
        ),
    ]
