# Generated by Django 4.2.3 on 2023-08-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_cpu_release_price_psu_release_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboardmodel',
            name='IO_connectors',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='PCIe_gen_support',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='chipset',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='model',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='ram_max_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='ram_max_frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='ram_slots_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='ram_type',
            field=models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='slots_and_connectors',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='socket',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='supported_cpus',
            field=models.ManyToManyField(to='hardware.cpu'),
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='brand',
            field=models.CharField(choices=[('Crucial', 'Crucial'), ('Hynix', 'Hynix'), ('Smart Modular', 'Smart Modular'), ('Kingston', 'Kingston'), ('Samsung', 'Samsung'), ('Team Group', 'Team Group'), ('PNY', 'PNY'), ('Micron', 'Micron'), ('Apacer', 'Apacer'), ('Qimonda', 'Qimonda'), ('Patriot', 'Patriot'), ('Transcend', 'Transcend'), ('ADATA', 'ADATA'), ('Corsair', 'Corsair'), ('G.Skill', 'G.Skill'), ('Mushkin', 'Mushkin'), ('GeIL', 'GeIL')], max_length=50),
        ),
    ]
