# Generated by Django 4.2.3 on 2023-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_motherboardmodel_image_alter_amdradeongpumodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboardmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='amdradeongpumodel',
            name='image',
            field=models.ImageField(upload_to='nvidia_gpu_images/'),
        ),
        migrations.AlterField(
            model_name='cpumodel',
            name='image',
            field=models.ImageField(upload_to='cpu_images/'),
        ),
        migrations.AlterField(
            model_name='nvidiagpumodel',
            name='image',
            field=models.ImageField(upload_to='nvidia_gpu_images/'),
        ),
        migrations.AlterField(
            model_name='psumodel',
            name='image',
            field=models.ImageField(upload_to='psu_images/'),
        ),
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('Qimonda', 'Qimonda'), ('Micron', 'Micron'), ('Samsung', 'Samsung'), ('Hynix', 'Hynix'), ('Team Group', 'Team Group'), ('Crucial', 'Crucial'), ('GeIL', 'GeIL'), ('PNY', 'PNY'), ('Apacer', 'Apacer'), ('ADATA', 'ADATA'), ('G.Skill', 'G.Skill'), ('Mushkin', 'Mushkin'), ('Smart Modular', 'Smart Modular'), ('Corsair', 'Corsair'), ('Patriot', 'Patriot'), ('Transcend', 'Transcend'), ('Kingston', 'Kingston')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rammemorymodel',
            name='image',
            field=models.ImageField(upload_to='ram_images/'),
        ),
        migrations.AlterField(
            model_name='storagedrivemodel',
            name='image',
            field=models.ImageField(upload_to='storage_drivers_images/'),
        ),
    ]
