# Generated by Django 4.2.3 on 2023-08-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_alter_rammemorymodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='rammemorymodel',
            name='model',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('Transcend', 'Transcend'), ('G.Skill', 'G.Skill'), ('PNY', 'PNY'), ('Crucial', 'Crucial'), ('Micron', 'Micron'), ('Corsair', 'Corsair'), ('Mushkin', 'Mushkin'), ('Hynix', 'Hynix'), ('Apacer', 'Apacer'), ('GeIL', 'GeIL'), ('ADATA', 'ADATA'), ('Patriot', 'Patriot'), ('Smart Modular', 'Smart Modular'), ('Team Group', 'Team Group'), ('Qimonda', 'Qimonda'), ('Samsung', 'Samsung'), ('Kingston', 'Kingston')], max_length=50),
        ),
    ]
