# Generated by Django 4.2.3 on 2023-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_rammemorymodel_model_alter_rammemorymodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('Kingston', 'Kingston'), ('G.Skill', 'G.Skill'), ('Micron', 'Micron'), ('Mushkin', 'Mushkin'), ('PNY', 'PNY'), ('Patriot', 'Patriot'), ('GeIL', 'GeIL'), ('Apacer', 'Apacer'), ('Transcend', 'Transcend'), ('Samsung', 'Samsung'), ('Smart Modular', 'Smart Modular'), ('Team Group', 'Team Group'), ('Hynix', 'Hynix'), ('Qimonda', 'Qimonda'), ('Crucial', 'Crucial'), ('Corsair', 'Corsair'), ('ADATA', 'ADATA')], max_length=50),
        ),
    ]
