# Generated by Django 4.2.3 on 2023-08-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_alter_rammemorymodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='amdradeongpumodel',
            name='price',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='image',
            field=models.ImageField(default=0, upload_to='motherboard_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='price',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='cpumodel',
            name='cores_count',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cpumodel',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cpumodel',
            name='release_price',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='motherboardmodel',
            name='IO_connectors',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='motherboardmodel',
            name='PCIe_gen_support',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motherboardmodel',
            name='ram_type',
            field=models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='motherboardmodel',
            name='slots_and_connectors',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='nvidiagpumodel',
            name='release_price',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='psumodel',
            name='manufacturer',
            field=models.CharField(choices=[('ABS', 'ABS'), ('MSI', 'MSI'), ('Antec', 'Antec'), ('AOpen', 'AOpen'), ('Apevia', 'Apevia'), ('AXLE', 'AXLE'), ('Be quiet!', 'Be quiet!'), ('Black Box', 'Black Box'), ('Cooler Master', 'Cooler Master'), ('Coolmax', 'Coolmax'), ('Corsair', 'Corsair'), ('Curtiss-Wright', 'Curtiss-Wright'), ('Deepcool', 'Deepcool'), ('Delta Electronics', 'Delta Electronics'), ('Dynapower USA', 'Dynapower USA'), ('Eaton', 'Eaton'), ('Emerson Network Power', 'Emerson Network Power'), ('EVGA', 'EVGA'), ('Foxconn', 'Foxconn'), ('G.SKILL', 'G.SKILL'), ('LIAN LI', 'LIANLI'), ('NZXT', 'NZXT'), ('Phanteks', 'Phanteks'), ('Qualstar', 'Qualstar'), ('RIOTORO', 'RIOTORO'), ('Rosewill', 'Rosewill'), ('Seasonic', 'Seasonic'), ('SIIG', 'SIIG'), ('Shuttle', 'Shuttle'), ('Supermicro', 'Supermicro'), ('TDK', 'TDK'), ('Thermaltake', 'Thermaltake'), ('UMEC', 'UMEC'), ('Vertiv', 'Vertiv'), ('XFX', 'XFX')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='psumodel',
            name='release_price',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='rammemorymodel',
            name='brand',
            field=models.CharField(choices=[('PNY', 'PNY'), ('Transcend', 'Transcend'), ('ADATA', 'ADATA'), ('Apacer', 'Apacer'), ('Crucial', 'Crucial'), ('Corsair', 'Corsair'), ('Team Group', 'Team Group'), ('Hynix', 'Hynix'), ('Mushkin', 'Mushkin'), ('GeIL', 'GeIL'), ('Patriot', 'Patriot'), ('Samsung', 'Samsung'), ('Micron', 'Micron'), ('Qimonda', 'Qimonda'), ('Kingston', 'Kingston'), ('Smart Modular', 'Smart Modular'), ('G.Skill', 'G.Skill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='storagedrivemodel',
            name='release_price',
            field=models.CharField(max_length=6),
        ),
    ]
