# Generated by Django 4.2.3 on 2023-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_basicuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
