# Generated by Django 4.2.3 on 2023-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_basicuser_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
