# Generated by Django 4.2.3 on 2023-07-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_basicuser_first_name_alter_basicuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='additional_information',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
    ]
