# Generated by Django 4.2.3 on 2023-07-28 15:40

import TonysHardware_v2.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_basicuser_additional_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/', validators=[TonysHardware_v2.accounts.models.validate_gallery_size])),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.AddConstraint(
            model_name='imagegallerymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('image__isnull', False)), fields=('user_profile',), name='user_gallery_limit'),
        ),
    ]
