# Generated by Django 4.2.3 on 2023-08-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageGalleryModel',
            new_name='UserImageGalleryModel',
        ),
    ]
