# Generated by Django 4.2.3 on 2023-08-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='article_images/')),
                ('content', models.TextField(max_length=500)),
                ('source', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
