# Generated by Django 4.2.3 on 2023-08-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_articlemodel_added_at_alter_articlemodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmodel',
            name='username',
        ),
    ]
